(IAC-1455) - Removal of Inappropriate Terminology
puppetlabs/puppet-resource_api pull request #283
Opened 2021-03-25 13:54 UTC by david22swan

Removal of any offensive or inappropriate terminology from the code base.

2021-03-25 13:57 UTC, DavidS requested changes

2021-03-25 13:57 UTC, DavidS commented on README.md
> +* The [Resource API specs](https://github.com/puppetlabs/puppet-specifications/blob/masmainter/language/resource-api/README.md) describes details of all the capabilities of this gem.
that repo hasn't change branches yet

2021-03-25 13:57 UTC, DavidS commented on appveyor.yml
> +#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/main/scripts/enable-rdp.ps1'))
that repo hasn't change branches yet

2021-03-25 14:16 UTC, david22swan commented on appveyor.yml
> +#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/main/scripts/enable-rdp.ps1'))
reverted

2021-03-25 14:16 UTC, david22swan commented on README.md
> +* The [Resource API specs](https://github.com/puppetlabs/puppet-specifications/blob/masmainter/language/resource-api/README.md) describes details of all the capabilities of this gem.
reverted

2021-03-30 09:25 UTC, david22swan commented
Unable to replicate failures locally

2021-04-07 10:28 UTC, david22swan commented
Current travis failures ticketed here and unrelated to PR: https://tickets.puppetlabs.com/browse/IAC-1556

2021-04-07 13:03 UTC, DavidS approved these changes

2021-04-07 13:03 UTC, merged